.PHONY: allcommands

server:
	python manage.py makemigrations
	python manage.py migrate
	python manage.py runserver

git:
	git add .
	git commit -m "Introduction to Building APIs with Django REST Framework"
	git push

